apiVersion: batch/v1
kind: CronJob
metadata:
  name: trivy-client
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: trivy-client
              image: sandeep97/trivy-acr-scanner:latest
              env:
               - name: LOAD_BALANCER_PUBLIC_IP
                 value: "20.204.221.104"
               - name: ACR_NAME
                 value: "tynybaytrivy"
               - name: AZURE_CLIENT_ID
                 valueFrom:
                   secretKeyRef:
                     name: service-principal-secret
                     key: clientid
               - name: AZURE_CLIENT_SECRET
                 valueFrom:
                   secretKeyRef:
                     name: service-principal-secret
                     key: clientsecret
               - name: AZURE_TENANT_ID
                 valueFrom:
                   secretKeyRef:
                     name: service-principal-secret
                     key: tenantid
               - name: STORAGE_ACCOUNT_NAME
                 valueFrom:
                   secretKeyRef:
                     name: azure-storage-secret
                     key: accountname
               - name: STORAGE_ACCOUNT_KEY
                 valueFrom:
                   secretKeyRef:
                     name: azure-storage-secret
                     key: accountkey
               - name: STORAGE_CONTAINER_NAME
                 valueFrom:
                   secretKeyRef:
                     name: azure-storage-secret
                     key: containername
              command: ["/bin/sh", "-c","/my_scripts/trivy-acr-scanner.sh"]
              volumeMounts:
                - name: config-volume
                  mountPath: /etc/trivy
                - name: azure-storage-secrets-volume
                  mountPath: /secrets
          volumes:
            - name: config-volume
              configMap:
                name: trivy-client-config 
            - name: azure-storage-secrets-volume
              secret:
                secretName: azure-storage-secret
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 1

