apiVersion: v1
kind: Secret
metadata:
  name: service-principal-secret
type: azurefile
stringData:
  clientid: f7224a41-62ca-4163-9334-d9f13e287b62
  clientsecret: 6qk8Q~rSkiOEQjy4bBeWQBFCxU6m1cCVMcO5Cas0
  tenantid: 5079d9f7-c62b-44a0-9332-cb7cd90373fe

