apiVersion: v1
kind: ConfigMap
metadata:
  name: trivy-client-config
data:
  config.yaml: |
    token:3a9c0d4d3e528e74797fb11863766a7e72124d1fb21fc3176f6013fa11091637c4376cdbec9003c1b9cc25958f53c6b6b13ce415edc85da8cb7a0c10eae57a71
    ignoreUnfixed: false
    insecure: false
    severity: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
    format: "template"
    outputTemplate: "{{ range .Results }}{{ .VulnerabilityID }}:{{ end }}"

