apiVersion: v1
kind: ConfigMap
metadata:
  name: trivy-client-config
data:
  config.yaml: |
    ignoreUnfixed: false
    insecure: false
    severity: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
    format: "template"
    outputTemplate: "{{ range .Results }}{{ .VulnerabilityID }}:{{ end }}"

