apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivy-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivy-server
  template:
    metadata:
      labels:
        app: trivy-server
    spec:
      containers:
      - name: trivy
        image: aquasec/trivy:latest
        command:
        - "/usr/local/bin/trivy"
        - "server"
        - "--listen"
        - "0.0.0.0:4954"
        - "--cache-dir"
        - "/var/cache/trivy"
        volumeMounts:
        - name: cache
          mountPath: /var/cache/trivy
      volumes:
      - name: cache
        emptyDir: {}
