apiVersion: v1
kind: Service
metadata:
  name: trivy-server-lb
spec:
  selector:
    app: trivy-server
  ports:
    - name: http
      port: 80
      targetPort: 4954
      protocol: TCP
  type: LoadBalancer

